# Generated by Django 4.2.7 on 2023-12-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.CharField(default='Calgary', max_length=50),
            preserve_default=False,
        ),
    ]
